name: qr_code_scanner_module
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  get: ^4.6.6
  qr_mobile_vision: ^4.1.3
  # UI
  fly_ui:
    git:
      url: git@github.com:niypoo/fly_ui.git
  # Config
  app_configuration_service:
    git: 
      url: git@github.com:niypoo/app_configuration_service.git


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0